# Generated by Django 4.2.5 on 2023-09-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customuser_username_messagemodel_createdat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='memory',
            field=models.TextField(null=True),
        ),
    ]
